<a href="https://colab.research.google.com/github/Barna036/Intro-to-Python1/blob/main/date_4_pyhton_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
for number in numbers:
    if number % 6 == 0:
        if number % 9 == 0:
            results.append(f"{number} is divisible by 6 and 9")
        else:
            results.append(f"{number} is divisible by 6")
    else:
        results.append(f"{number} is not divisible by 6")
return results

is_div_six(my_list)

In [ ]:
## or we could just do a list comprehension

def is_div_six(number):
    if number % 6 == 0:
        if number % 9 == 0:
            return f"{number} is divisible by 6 and 9"
        else:
            return f"{number} is divisible by 6"
    else:
        return f"{number} is not divisible by 6"

[is_div_six(n) for n in my_list]


Write a function that, given a dictionary consisting of policies and their budgets in millions of dollars, constructs a list of the policy names with budgets below $100 million.

Use the following dictionary of policies


In [18]:
#Day 4
policies = {"public_transit": 10, "education_funding": 50, "snap_expansion": 175,
            "defense_procurement": 850, "reduce_emissions": 20,
            "judicial_modernization": 35, "broadband_access": 250, "school_lunches": 80}
def cheap_policies(policies):
    my_policies = {}
    for policy, cost in policies.items():
        if cost < 100:
            my_policies.update({policy: cost}) # key value use : not comma
    return my_policies

cheap_policies(policies)
# def cheap_policies(policies):
# my_policies = {}


# for my_policies in policies:
#     if policies[my_policies] < 100:
#         print(my_policies)
# cheap_policies(policies)

#   for policy in policies:
#     if policies[policy] > 100:
#       print(policy)

# expensive_policies()

{'public_transit': 10,
 'education_funding': 50,
 'reduce_emissions': 20,
 'judicial_modernization': 35,
 'school_lunches': 80}

You Try

Write a list comprehension that takes some list of numbers, and subtracts 5 from only the numbers that are divisible by 3.

In [20]:
some_numbers = [ 3, 15, 12, 8, 11]
new_list = [number - 5 for number in some_numbers if number % 3 == 0]
new_list
# start with from where we want to get out of it, I want something 5 - divisbile by 3

[-2, 10, 7]

# Conditional Logic in Comprehensions
Suppose we have multiple conditions we want to evaluate. In a for loop we would use if, elif and else, but the syntax is a little different for comprehensions. Check out this more complicated syntax.

In [21]:
# conditional logic in comprehension

policies = ["Public Transit", "Education Funding", "SNAP Expansion", "Defense Procurement", "Reduce Emissions"]
budgets  = [10,                50,                  175,              850,                   20]  # in millions of dollars


classifications = [
    f"{name}: " + (
        "small"   if budget < 25
        else "medium" if budget < 100
        else "large"
    )
    for name, budget in zip(policies, budgets)
]

print(classifications)

['Public Transit: small', 'Education Funding: medium', 'SNAP Expansion: large', 'Defense Procurement: large', 'Reduce Emissions: small']


In [23]:
policy_budget = {"public_transit": 10, "education_funding": 50, "snap_expansion": 175,
            "defense_procurement": 850, "reduce_emissions": 20}

classiciation= {
            key: (
                "small" if value <25
                else "medium" if value < 100
                else "large"

            ) #key then colon
    for key, value in policy_budget.items ()
            }
classifications


['Public Transit: small',
 'Education Funding: medium',
 'SNAP Expansion: large',
 'Defense Procurement: large',
 'Reduce Emissions: small']

## Review Exercise Revisited for dictionary comprehensioon

Write a function that, given a dictionary consisting of policies and their budgets in millions, constructs a dictionary of policies with budgets below $100 million. Use a comprehension to accomplish this!

Start with

In [24]:
policies = {"public_transit": 10, "education_funding": 50, "snap_expansion": 175,
            "defense_procurement": 850, "reduce_emissions": 20,
            "judicial_modernization": 35, "broadband_access": 250, "school_lunches": 80}
cheap_policies={
    key: value
    for key, value in policies.items()
    if value < 100
}
cheap_policies

{'public_transit': 10,
 'education_funding': 50,
 'reduce_emissions': 20,
 'judicial_modernization': 35,
 'school_lunches': 80}

In [ ]:
# this packs loops, dictonary and
# py function .nypy for save
# pyhton modules: the standard library

# pyhton modules: the standard library

Python Modules
Python modules are files (.py) that (mainly) contain function definitions

they allow us to organize, distribute code; to share and reuse others’ code too

Can easily create, save and load our own custom modules
keep code coherent and self-contained

one can import modules or some functions from modules

In [25]:
import math
math.pow(2,3) # rais ea number to a function
#without it simply I can write, 2**3
# def raise_to_power(a, b):
#     return a**b
# raise_to_power(2, 3)

8.0

In [29]:
#another example (daytime)

from datetime import date

today = date.today()

print("Today's date is:", today)

Today's date is: 2026-07-09


## NumPy
NumPy is short for numerical Python. It’s a foundational package for data analysis in Python, and many packages depend on numpy arrays as a data type.

Many later libraries, like pandas, are built on the functions and data structures of NumPy. Machine learning frameworks like tensorflow also build on this infrastructure.

The most common and useful data structure in NumPy is the array. Arrays are structured objects in Python that contain data of all the same type.

### Importing Libraries
numpy is not a built-in feature of Python, so we need to load it. If you don’t have it installed, type pip install numpy in your terminal.

**By convention we load numpy as np.**

In [31]:
# create an array
# create an array of data
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5], [5,8,9]])

data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5],
       [ 5. ,  8. ,  9. ]])

In [35]:
data * 10
data + 5
data * data  # elementwise multiplciation

array([[2.250e+00, 1.000e-02, 9.000e+00],
       [0.000e+00, 9.000e+00, 4.225e+01],
       [2.500e+01, 6.400e+01, 8.100e+01]])

In [37]:
data.shape # how many rows and columns
data.dtype # what is this?

dtype('float64')

In [39]:
np.zeros ((2,3,2)) # two different 3 by 3 dimension staff
np.arange(20) # ordered array from 0 to 19

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
# slice an index array
arr= np.arange(20)
arr[8: 18]
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# Warning!
You do need to be careful with slicing arrays. Even if you save a slice of an array to a new object, NumPy still recognizes that slice as part of the original array. And if you change the values in that new object, it will also change the original object in

In [ ]:
# uh-oh

arr_slice = arr[5:8]
arr_slice

arr_slice[1] = 12345

arr

Fixing the Copy Problem
If you want an independent copy of the slice, use .copy():

arr = np.arange(10)
arr_slice = arr[5:8].copy()

arr_slice[1] = 12345
print("slice:   ", arr_slice)
print("original:", arr)

slice:    [    5 12345     7]
original: [0 1 2 3 4 5 6 7 8 9]
Now the slice is a completely separate array — changes to arr_slice don’t touch arr.

Rule of thumb: if you’ll be modifying the slice, call .copy(). If you’re only reading from it, you don’t need to

#solution
always use .copy
https://numpy.org/doc/stable/reference/generated/numpy.arange.html

You can find more about np.arrange. np.arange(3,7). This code will change the start point.

In [49]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr_3d[1:, :2, 1:] # need to check and understand this.

array([[[ 8,  9],
        [11, 12]]])

In [54]:
# Universal array
arr1= np.random.standard_normal (10)
arr2=np.random.standard_normal (10)
#np.add(arr1,arr2)
#np.multiply(arr1,arr2)
np.maximum(arr1,arr2)
#add seed for random seed

array([ 1.02521041,  0.06390363,  1.56544402, -0.1446097 ,  0.21293643,
        2.50846066,  1.34843708, -0.59058492,  0.88290233, -0.74598192])

In [ ]:
#check McKinney book section 4.3 for a look at their universal code

# Pandas
pandas
pandas is the most popular data analysis package in Python. It is not the only option — Polars, which has syntax more similar to the tidyverse, is gaining popularity.

But pandas is still dominant. It is great for loading and cleaning data, as well as basic data analyses. Most advanced analyses packages, including machine learning packages like PyTorch and TensorFlow, build on pandas and numpy.

By convention, we import pandas as pd

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')